services:
  - type: web
    name: flippa-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome